using System;
using System.Collections.Generic;

namespace BalanceGlobal.Database.Tables
{
    public partial class SourceNovt
    {
        public long _0IdSincronizacionCorfo { get; set; }
        public Guid _0IdMensaje { get; set; }
        public string _0NombreTabla { get; set; }
        public string _0TipoTransaccion { get; set; }
        public string _0Observacion { get; set; }
        public string _1IdVariable { get; set; }
        public string _1Descripcion { get; set; }
        public DateTime? _1Fecha { get; set; }
        public decimal? _1Valor { get; set; }
        public decimal? _1ResultNumber { get; set; }
        public string _1SValor { get; set; }
        public string _2IdVariable { get; set; }
        public string _2Area { get; set; }
        public string _2DescVariable { get; set; }
        public string _2Descripcion { get; set; }
        public long? _3Id { get; set; }
        public long? _3AmbientalControlPointId { get; set; }
        public DateTime? _3TimeStamp { get; set; }
        public DateTime? _3CreatedAt { get; set; }
        public DateTime? _3UpdatedAt { get; set; }
        public long? _3SectorId { get; set; }
        public decimal? _3PlantOrPoolExtraction { get; set; }
        public long? _4Id { get; set; }
        public string _4Name { get; set; }
        public long? _4TypeId { get; set; }
        public long? _4ClasificationId { get; set; }
        public long? _4DescriptionId { get; set; }
        public long? _4SectorId { get; set; }
        public long? _4DestinationId { get; set; }
        public DateTime? _4CreatedAt { get; set; }
        public DateTime? _4UpdatedAt { get; set; }
        public long? _4PumpId { get; set; }
        public long? _4LocationId { get; set; }
        public bool? _4IsEnabled { get; set; }
        public int? _4ExtractionRights { get; set; }
        public string _4Label { get; set; }
        public string _4Lat { get; set; }
        public string _4Lng { get; set; }
        public DateTime? _4WorkingFrom { get; set; }
        public DateTime? _4WorkingUntil { get; set; }
        public long? _5Id { get; set; }
        public decimal? _5F1 { get; set; }
        public decimal? _5F2 { get; set; }
        public decimal? _5BrineDensity { get; set; }
        public decimal? _5SaltDensity { get; set; }
        public decimal? _5IbaSop { get; set; }
        public decimal? _5IbaMop { get; set; }
        public DateTime? _5CreatedAt { get; set; }
        public DateTime? _5UpdatedAt { get; set; }
        public bool? _5IsEnabled { get; set; }
        public decimal? _5LitersPerSecond { get; set; }
        public long? _6Id { get; set; }
        public decimal? _6PoolExtraction { get; set; }
        public decimal? _6PlantExtraction { get; set; }
        public decimal? _6PulpFlowDps { get; set; }
        public decimal? _6PorcentSolidPulpDps { get; set; }
        public decimal? _6EvaporationStationKci { get; set; }
        public decimal? _6LagoonArea { get; set; }
        public decimal? _6ImpregnatedBrineAreaDps { get; set; }
        public decimal? _6RecycleBrineDps { get; set; }
        public decimal? _6TotalExtraction { get; set; }
        public decimal? _6BrineDps { get; set; }
        public decimal? _6EvaporationExposedBrineDps { get; set; }
        public decimal? _6EvaporationExposedAreaDps { get; set; }
        public decimal? _6EvaporationBrineImpregnatedDps { get; set; }
        public decimal? _6EvaporationAreaImpregnatedDps { get; set; }
        public decimal? _6IndirectReinjection { get; set; }
        public decimal? _6NetExtractionMD { get; set; }
        public decimal? _6NetExtractionLS { get; set; }
        public DateTime? _6CreatedAt { get; set; }
        public DateTime? _6UpdatedAt { get; set; }
        public DateTime? _6TimeStamp { get; set; }
        public long? _6SectorId { get; set; }
        public long? _6ConstantId { get; set; }
        public bool? _6IsProcessing { get; set; }
        public bool? _6IsOficial { get; set; }
        public bool? _6IsOficialDatum { get; set; }
        public decimal? _6DirectReinjection { get; set; }
        public long? _7Id { get; set; }
        public string _7Name { get; set; }
        public DateTime? _7CreatedAt { get; set; }
        public DateTime? _7UpdatedAt { get; set; }
        public long? _8Id { get; set; }
        public string _8ItemType { get; set; }
        public long? _8ItemId { get; set; }
        public string _8Event { get; set; }
        public string _8Whodunnit { get; set; }
        public string _8Object { get; set; }
        public string _8Comment { get; set; }
        public DateTime? _8CreatedAt { get; set; }
        public long? _9Id { get; set; }
        public double? _9AverageFlowDay { get; set; }
        public double? _9FlowDay { get; set; }
        public DateTime? _9TimeStamp { get; set; }
        public DateTime? _9CreatedAt { get; set; }
        public DateTime? _9UpdatedAt { get; set; }
        public long? _9AmbientalControlPointId { get; set; }
        public bool? _9IsProcessing { get; set; }
        public string _10Infraestructura { get; set; }
        public DateTime? _10Fecha { get; set; }
        public string _10TipoEnsayo { get; set; }
        public string _10MetodoFisico { get; set; }
        public decimal? _10Valor { get; set; }
        public string _10Unidad { get; set; }
        public string _10Empresa { get; set; }
        public bool? _10Validado { get; set; }
        public bool? _10Publicado { get; set; }
        public bool? _10Modificado { get; set; }
        public string _10Comentario { get; set; }
        public bool? _10Log { get; set; }
        public bool? _10Eliminado { get; set; }
        public int? _10IdAforo { get; set; }
        public string _11Infraestructura { get; set; }
        public DateTime? _11Fecha { get; set; }
        public string _11Laboratorio { get; set; }
        public string _11Analito { get; set; }
        public string _11Descriptor { get; set; }
        public decimal? _11Valor { get; set; }
        public string _11Unidad { get; set; }
        public bool? _11Validado { get; set; }
        public bool? _11Publicado { get; set; }
        public bool? _11Modificado { get; set; }
        public string _11Comentario { get; set; }
        public bool? _11Log { get; set; }
        public bool? _11Eliminado { get; set; }
        public int? _11IdAnalisisQuimico { get; set; }
        public string _12Infraestructura { get; set; }
        public decimal? _12UtmNorte { get; set; }
        public decimal? _12UtmEste { get; set; }
        public decimal? _12CotaPuntoReferenciaMsnm { get; set; }
        public DateTime? _12InicioVigencia { get; set; }
        public DateTime? _12TerminoVigencia { get; set; }
        public bool? _12Log { get; set; }
        public bool? _12Eliminado { get; set; }
        public int? _12IdCoordenada { get; set; }
        public string _13Infraestructura { get; set; }
        public DateTime? _13Fecha { get; set; }
        public string _13TipoEnsayo { get; set; }
        public decimal? _13Profundidad { get; set; }
        public decimal? _13Valor { get; set; }
        public string _13Unidad { get; set; }
        public string _13Empresa { get; set; }
        public bool? _13Validado { get; set; }
        public bool? _13Publicado { get; set; }
        public bool? _13Modificado { get; set; }
        public string _13Comentario { get; set; }
        public bool? _13Log { get; set; }
        public bool? _13Eliminado { get; set; }
        public int? _13IdCuna { get; set; }
        public string _18Estacion { get; set; }
        public DateTime? _18Fecha { get; set; }
        public string _18Parametro { get; set; }
        public decimal? _18Valor { get; set; }
        public string _18Unidad { get; set; }
        public string _18Frecuencia { get; set; }
        public string _18TipoDato { get; set; }
        public bool? _18Validado { get; set; }
        public bool? _18Publicado { get; set; }
        public bool? _18Modificado { get; set; }
        public string _18Comentario { get; set; }
        public bool? _18Log { get; set; }
        public bool? _18Eliminado { get; set; }
        public int? _18IdMedicionEstacion { get; set; }
        public string _19Infraestructura { get; set; }
        public DateTime? _19Fecha { get; set; }
        public string _19TipoNivel { get; set; }
        public string _19ModalidadNivel { get; set; }
        public decimal? _19MedicionBajoPuntoReferenciaM { get; set; }
        public decimal? _19CotaPuntoReferenciaMsnm { get; set; }
        public decimal? _19CotaNivelMsnm { get; set; }
        public decimal? _19NivelRelativo { get; set; }
        public decimal? _19Nbprinicial { get; set; }
        public string _19Empresa { get; set; }
        public bool? _19PlanContingencia { get; set; }
        public bool? _19Validado { get; set; }
        public bool? _19Publicado { get; set; }
        public bool? _19Modificado { get; set; }
        public string _19Comentario { get; set; }
        public bool? _19Log { get; set; }
        public bool? _19Eliminado { get; set; }
        public int? _19IdNivel { get; set; }
        public string _20Infraestructura { get; set; }
        public DateTime? _20Fecha { get; set; }
        public string _20TipoNivel { get; set; }
        public string _20ModalidadNivel { get; set; }
        public decimal? _20MedicionBajoPuntoReferenciaM { get; set; }
        public decimal? _20CotaPuntoReferenciaMsnm { get; set; }
        public decimal? _20CotaNivelMsnm { get; set; }
        public decimal? _20NivelRelativo { get; set; }
        public decimal? _20Nbprinicial { get; set; }
        public string _20Empresa { get; set; }
        public bool? _20PlanContingencia { get; set; }
        public bool? _20Validado { get; set; }
        public bool? _20Publicado { get; set; }
        public bool? _20Modificado { get; set; }
        public string _20Comentario { get; set; }
        public bool? _20Log { get; set; }
        public bool? _20Eliminado { get; set; }
        public int? _20IdNivel { get; set; }
        public string _21Infraestructura { get; set; }
        public DateTime? _21FechaVigencia { get; set; }
        public string _21Sistema { get; set; }
        public string _21Subsistema { get; set; }
        public decimal? _21DescensoFaseI { get; set; }
        public decimal? _21DescensoFaseIi { get; set; }
        public decimal? _21CotaFaseI { get; set; }
        public decimal? _21CotaFaseIi { get; set; }
        public decimal? _21GrafInferior { get; set; }
        public decimal? _21GrafSuperior { get; set; }
        public bool? _21Log { get; set; }
        public bool? _21Eliminado { get; set; }
        public int? _21IdTauxiliar { get; set; }
        public string _22Infraestructura { get; set; }
        public DateTime? _22Fecha { get; set; }
        public string _22TipoEnsayo { get; set; }
        public string _22TipoMetodo { get; set; }
        public decimal? _22Valor { get; set; }
        public string _22Unidad { get; set; }
        public string _22Empresa { get; set; }
        public bool? _22Validado { get; set; }
        public bool? _22Publicado { get; set; }
        public bool? _22Modificado { get; set; }
        public string _22Comentario { get; set; }
        public bool? _22Log { get; set; }
        public bool? _22Eliminado { get; set; }
        public int? _22IdSuperficieLacustre { get; set; }
    }
}
